// Code generated by MockGen. DO NOT EDIT.
// Source: application/product.go

// Package mock_application is a generated GoMock package.
package mock_application

import (
	reflect "reflect"

	application "github.com/full-cycle-2.0-hexagonal-architecture/application"
	gomock "github.com/golang/mock/gomock"
)

// MockIProduct is a mock of IProduct interface.
type MockIProduct struct {
	ctrl     *gomock.Controller
	recorder *MockIProductMockRecorder
}

// MockIProductMockRecorder is the mock recorder for MockIProduct.
type MockIProductMockRecorder struct {
	mock *MockIProduct
}

// NewMockIProduct creates a new mock instance.
func NewMockIProduct(ctrl *gomock.Controller) *MockIProduct {
	mock := &MockIProduct{ctrl: ctrl}
	mock.recorder = &MockIProductMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIProduct) EXPECT() *MockIProductMockRecorder {
	return m.recorder
}

// Disable mocks base method.
func (m *MockIProduct) Disable() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Disable")
	ret0, _ := ret[0].(error)
	return ret0
}

// Disable indicates an expected call of Disable.
func (mr *MockIProductMockRecorder) Disable() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disable", reflect.TypeOf((*MockIProduct)(nil).Disable))
}

// Enable mocks base method.
func (m *MockIProduct) Enable() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enable")
	ret0, _ := ret[0].(error)
	return ret0
}

// Enable indicates an expected call of Enable.
func (mr *MockIProductMockRecorder) Enable() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enable", reflect.TypeOf((*MockIProduct)(nil).Enable))
}

// GetId mocks base method.
func (m *MockIProduct) GetId() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetId")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetId indicates an expected call of GetId.
func (mr *MockIProductMockRecorder) GetId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetId", reflect.TypeOf((*MockIProduct)(nil).GetId))
}

// GetName mocks base method.
func (m *MockIProduct) GetName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName.
func (mr *MockIProductMockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockIProduct)(nil).GetName))
}

// GetPrice mocks base method.
func (m *MockIProduct) GetPrice() float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrice")
	ret0, _ := ret[0].(float64)
	return ret0
}

// GetPrice indicates an expected call of GetPrice.
func (mr *MockIProductMockRecorder) GetPrice() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrice", reflect.TypeOf((*MockIProduct)(nil).GetPrice))
}

// GetStatus mocks base method.
func (m *MockIProduct) GetStatus() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockIProductMockRecorder) GetStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockIProduct)(nil).GetStatus))
}

// IsValid mocks base method.
func (m *MockIProduct) IsValid() (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsValid")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsValid indicates an expected call of IsValid.
func (mr *MockIProductMockRecorder) IsValid() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsValid", reflect.TypeOf((*MockIProduct)(nil).IsValid))
}

// MockIProduceService is a mock of IProduceService interface.
type MockIProduceService struct {
	ctrl     *gomock.Controller
	recorder *MockIProduceServiceMockRecorder
}

// MockIProduceServiceMockRecorder is the mock recorder for MockIProduceService.
type MockIProduceServiceMockRecorder struct {
	mock *MockIProduceService
}

// NewMockIProduceService creates a new mock instance.
func NewMockIProduceService(ctrl *gomock.Controller) *MockIProduceService {
	mock := &MockIProduceService{ctrl: ctrl}
	mock.recorder = &MockIProduceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIProduceService) EXPECT() *MockIProduceServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIProduceService) Create(name string, price float64) (application.IProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", name, price)
	ret0, _ := ret[0].(application.IProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIProduceServiceMockRecorder) Create(name, price interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIProduceService)(nil).Create), name, price)
}

// Disable mocks base method.
func (m *MockIProduceService) Disable(product application.IProduct) (application.IProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Disable", product)
	ret0, _ := ret[0].(application.IProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Disable indicates an expected call of Disable.
func (mr *MockIProduceServiceMockRecorder) Disable(product interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disable", reflect.TypeOf((*MockIProduceService)(nil).Disable), product)
}

// Enable mocks base method.
func (m *MockIProduceService) Enable(product application.IProduct) (application.IProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enable", product)
	ret0, _ := ret[0].(application.IProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enable indicates an expected call of Enable.
func (mr *MockIProduceServiceMockRecorder) Enable(product interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enable", reflect.TypeOf((*MockIProduceService)(nil).Enable), product)
}

// Get mocks base method.
func (m *MockIProduceService) Get(id string) (application.IProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(application.IProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIProduceServiceMockRecorder) Get(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIProduceService)(nil).Get), id)
}

// MockIProductReader is a mock of IProductReader interface.
type MockIProductReader struct {
	ctrl     *gomock.Controller
	recorder *MockIProductReaderMockRecorder
}

// MockIProductReaderMockRecorder is the mock recorder for MockIProductReader.
type MockIProductReaderMockRecorder struct {
	mock *MockIProductReader
}

// NewMockIProductReader creates a new mock instance.
func NewMockIProductReader(ctrl *gomock.Controller) *MockIProductReader {
	mock := &MockIProductReader{ctrl: ctrl}
	mock.recorder = &MockIProductReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIProductReader) EXPECT() *MockIProductReaderMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockIProductReader) Get(id string) (application.IProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(application.IProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIProductReaderMockRecorder) Get(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIProductReader)(nil).Get), id)
}

// MockIProductWriter is a mock of IProductWriter interface.
type MockIProductWriter struct {
	ctrl     *gomock.Controller
	recorder *MockIProductWriterMockRecorder
}

// MockIProductWriterMockRecorder is the mock recorder for MockIProductWriter.
type MockIProductWriterMockRecorder struct {
	mock *MockIProductWriter
}

// NewMockIProductWriter creates a new mock instance.
func NewMockIProductWriter(ctrl *gomock.Controller) *MockIProductWriter {
	mock := &MockIProductWriter{ctrl: ctrl}
	mock.recorder = &MockIProductWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIProductWriter) EXPECT() *MockIProductWriterMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockIProductWriter) Save(product application.IProduct) (application.IProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", product)
	ret0, _ := ret[0].(application.IProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockIProductWriterMockRecorder) Save(product interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIProductWriter)(nil).Save), product)
}

// MockIProductPersistence is a mock of IProductPersistence interface.
type MockIProductPersistence struct {
	ctrl     *gomock.Controller
	recorder *MockIProductPersistenceMockRecorder
}

// MockIProductPersistenceMockRecorder is the mock recorder for MockIProductPersistence.
type MockIProductPersistenceMockRecorder struct {
	mock *MockIProductPersistence
}

// NewMockIProductPersistence creates a new mock instance.
func NewMockIProductPersistence(ctrl *gomock.Controller) *MockIProductPersistence {
	mock := &MockIProductPersistence{ctrl: ctrl}
	mock.recorder = &MockIProductPersistenceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIProductPersistence) EXPECT() *MockIProductPersistenceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockIProductPersistence) Get(id string) (application.IProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(application.IProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIProductPersistenceMockRecorder) Get(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIProductPersistence)(nil).Get), id)
}

// Save mocks base method.
func (m *MockIProductPersistence) Save(product application.IProduct) (application.IProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", product)
	ret0, _ := ret[0].(application.IProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockIProductPersistenceMockRecorder) Save(product interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIProductPersistence)(nil).Save), product)
}
